services:
  postgresdb:
    image: postgres:15-alpine
    env_file:
      - ./prod.env
    ports:
      - "5433:5432"
    restart: unless-stopped
# ------------------------------------------------------------------------------------------------------------------
  web:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile.prod
      args:
        - REACT_APP_API_URL=http://localhost:80
        - REACT_APP_WSO2_CLIENT_ID=agh44RajMJcYvCIq3lSMrutfPJ0a
        - REACT_APP_WSO2_REDIRECT_URI=http://localhost:80/
        - REACT_APP_IDP_URI=https://wso2-gw.ua.pt/
        - REACT_APP_IDP_BASE64=Basic YWdoNDRSYWpNSmNZdkNJcTNsU01ydXRmUEowYTpXSmNrVTBGU2I0MXJzSkhMbkZQWXFCRnZTWm9h
    restart: unless-stopped
    env_file:
      - ./prod.env
    ports:
      - 80:80
    depends_on:
      - postgresdb
      - springboot

# ------------------------------------------------------------------------------------------------------------------
  springboot:
    depends_on:
      - postgresdb
    build: 
      context: ./backend/uasmartsignage
      dockerfile: Dockerfile.prod
    env_file:
      - ./prod.env
    ports:
      - 8080:8080
# ------------------------------------------------------------------------------------------------------------------
  influxdb:
    image: influxdb:2.1.1
    env_file:
      - ./prod.env
    volumes:
        - influxdb_data:/var/lib/influxdb
    ports:
        - 8086:8086

  influxdb_cli:
    build: .
    env_file:
      - ./prod.env
    links:
      - influxdb
    volumes:
      - ./influxdbv2:/root/.influxdbv2
    entrypoint: ["./docker-entrypoint-initdb.d/entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb
# ------------------------------------------------------------------------------------------------------------------
  mosquitto:
    image: eclipse-mosquitto:latest
    env_file:
      - ./prod.env
    volumes:
      - ./mosquitto/passwd:/mosquitto/config/passwd
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
        - 9001:9001
        - 1883:1883
    
volumes:
    influxdb_data: