services:
  postgresdb:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./dev.env
    ports:
      - 5432:5432
    networks:
      - mqttnet
      
  springboot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    env_file:
      - ./dev.env
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on:
      - postgresdb
      - mosquitto
    networks:
      - mqttnet
      
  influxdb:
    image: influxdb:2.1.1
    env_file:
      - ./dev.env
    volumes:
        - influxdb_data:/var/lib/influxdb
    networks:
        - mqttnet
    ports:
        - 8086:8086
        
  influxdb_cli:
    build: .
    env_file:
      - ./dev.env
    links:
      - influxdb
    volumes:
      - ./influxdbv2:/root/.influxdbv2
    entrypoint: ["./docker-entrypoint-initdb.d/entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb
    networks:
      - mqttnet

  mosquitto:
    image: eclipse-mosquitto:1.6.13
    volumes:
        - mosquitto_conf:/mosquitto/config 
        - mosquitto_data:/mosquitto/data
        - mosquitto_log:/mosquitto/log
    networks:
        - mqttnet
    ports:
        - 9001:9001
        - 1883:1883
    env_file:
      - ./dev.env

  web:
      depends_on:
          - postgresdb
          - springboot
          - mosquitto
      build:
        context: ./frontend
        dockerfile: .docker/Dockerfile
      restart: unless-stopped
      env_file:
        - ./dev.env
      volumes:
        - "./frontend/:/app"
      ports:
        - 8000:8000
      command: >
        bash -c "pnpm run dev"

volumes:
    mosquitto_conf:
    mosquitto_data:
    mosquitto_log:
    influxdb_data:

networks:
  mqttnet:
    driver: bridge
