version: "3.9"
services:
  sonarqube:
    image: "sonarqube:latest"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - 9000:9000

  frontend:
    depends_on:
        - sonarqube
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - PROJECT=${PROJECT}
    volumes:
      - "./frontend/:/app"
    ports:
      - 3000:3000
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && sleep 25
      && node sonarqube/sonarscan.js"