version: "9.3"
services:
  sonarqube:
    image: "sonarqube:9.9.4-community"
    volumes:
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/data:/opt/sonarqube/data
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLED=true
    expose:
      - "9000"
    ports:
      - 9000:9000

  frontend:
    depends_on:
        - sonarqube
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    volumes:
      - "./frontend/:/app"
    ports:
      - 3000:3000
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
      && npm scan"