version: '3.9'

services:
  postgres_db:  # Renamed the service to postgres_db
    image: postgres:latest  # Using the PostgreSQL image
    restart: unless-stopped
    env_file:
      - credentials.env
    ports:
      - "5432:5432"
    networks:
      - mqttnet

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on:
      - postgres_db
      - mqtt
    networks:
      - mqttnet #default

  mqtt:
    image: eclipse-mosquitto:1.6.13
    volumes:
        - mosquitto_conf:/mosquitto/config 
        - mosquitto_data:/mosquitto/data
        - mosquitto_log:/mosquitto/log
    networks:
        - mqttnet
    ports:
        - 9001:9001
        - 1883:1883

volumes:
    mosquitto_conf:
    mosquitto_data:
    mosquitto_log:

networks:
  mqttnet:
    driver: bridge