version: '3.9'

services:
  postgres_db:  # Renamed the service to postgres_db
    image: postgres:latest  # Using the PostgreSQL image
    restart: unless-stopped
    env_file:
      - credentials.env
    ports:
      - "5432:5432"
    networks:
      - default

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005