version: '3.9'

services:
  postgres_db:  # Renamed the service to postgres_db
    image: postgres:latest  # Using the PostgreSQL image
    restart: unless-stopped
    environment:
      POSTGRES_DB: uas
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: springpass
    ports:
      - "5432:5432"
    networks:
      - default

  mongodb:
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpass
        MONGO_INITDB_DATABASE: admin
    ports:
        - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default

  spring:
    build: .
    container_name: spring
    ports:
      - 8080:8080
    restart: unless-stopped
    image: uas
    expose:
      - 8080
    networks:
      - default